import "@/app/globals.css";
import { NextAuthProvider } from "@/providers/NextAuthProvider";


export const metadata = {
  title: "Create Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        # TODO: Put results of if the user is washed or not here.
        <p>This is an authenticated view.</p>
      </NextAuthProvider>
    </html>
  );
}